#!/bin/sh
set -ea

echo "Running directus!"

DIRECTUS_ADMIN_EMAIL="${DIRECTUS_ADMIN_EMAIL:-admin@admin.com}"
DIRECTUS_ADMIN_PASSWORD="${DIRECTUS_ADMIN_PASSWORD:-admin}"
DIRECTUS_SITE_NAME="${DIRECTUS_SITE_NAME:-directus}"

is_elasticbeanstalk(){
  if [ -z ${RDS_DB_NAME+x} ]; then
    return 1
  else
    return 0
  fi
}

is_linked_container(){
  if [ -z ${MYSQL_ENV_MYSQL_DATABASE+x} ]; then
    return 1
  else
    return 0
  fi
}

is_database_installed(){
  #tables=$(mysql -D $DIRECTUS_DB_SCHEMA -h $DIRECTUS_DB_HOST -u$DIRECTUS_DB_USER -P $DIRECTUS_DB_PORT -p$DIRECTUS_DB_PASSWORD --batch --skip-column-names -e "show tables")

  script="\$c = mysqli_connect(\"$DIRECTUS_DB_HOST\", \"$DIRECTUS_DB_USER\", \"$DIRECTUS_DB_PASSWORD\");\$r = mysqli_query(\$c,\"SHOW TABLES FROM $DIRECTUS_DB_SCHEMA\");if(\$r === false){return;} while(\$t = mysqli_fetch_array(\$r)) {echo \$t[0].\"\n\";} mysqli_close(\$c);"
  echo $script;

  tables=$(php -r "$script");
  echo $tables;

  if [ -z "$tables" ]; then
    return 1
  else
    return 0
  fi

}


if is_elasticbeanstalk ; then
    DIRECTUS_DB_SCHEMA=$RDS_DB_NAME
    DIRECTUS_DB_HOST=$RDS_HOSTNAME
    DIRECTUS_DB_PORT=$RDS_PORT
    DIRECTUS_DB_PASSWORD=$RDS_PASSWORD
    DIRECTUS_DB_USER=$RDS_USERNAME
fi

if is_linked_container ; then
    DIRECTUS_DB_SCHEMA=$MYSQL_ENV_MYSQL_DATABASE
    DIRECTUS_DB_HOST=$MYSQL_PORT_3306_TCP_ADDR
    DIRECTUS_DB_PORT=$MYSQL_PORT_3306_TCP_PORT
    DIRECTUS_DB_PASSWORD=$MYSQL_ENV_MYSQL_PASSWORD
    DIRECTUS_DB_USER=$MYSQL_ENV_MYSQL_USER
fi


if [ ! -d $WEBROOT/vendor ]; then
  composer --working-dir="$WEBROOT" install
fi

#$WEBROOT/bin/directus install:config -h "$DIRECTUS_DB_HOST" -n "$DIRECTUS_DB_SCHEMA" -u "$DIRECTUS_DB_USER" -p "$DIRECTUS_DB_PASSWORD" -d "$DIRECTUS_PATH"
$WEBROOT/bin/directus install:config -h "$DIRECTUS_DB_HOST" -n "$DIRECTUS_DB_SCHEMA" -u "$DIRECTUS_DB_USER" -p "$DIRECTUS_DB_PASSWORD"

if ! is_database_installed ; then
  $WEBROOT/bin/directus install:database
  $WEBROOT/bin/directus install:install -e "$DIRECTUS_ADMIN_EMAIL" -p "$DIRECTUS_ADMIN_PASSWORD" -t "$DIRECTUS_SITE_NAME"
fi

# rm -R -f $WEBROOT/installation/*

EXIT_STATUS=0
